version: '3.8'

services:

  mdp-client:
    container_name: mdp-client
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-server
    ports:
      - '80:80'
      - '443:443'
    networks:
      - internal-client
    environment:
      - NODE_ENV=production

  mdp-server:
    container_name: mdp-server
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-mongo
    ports:
      - '5000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.production
    networks:
      - default
      - internal-client

  mdp-mongo:
    image: mongo
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017'
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123
    volumes:
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    networks:
      - default

networks:
  default:
    name: mdp-default
  internal-client:
    name: mdp-client
