version: '3.8'

services:
  mdp-client:
    container_name: mdp-client
    restart: unless-stopped
    build:
      # src must be in context
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-server
    # nginx ports
    ports:
      - '80:80'
      - '443:443'
    networks:
      - internal-client
    environment:
      - NODE_ENV=production

  mdp-server:
    container_name: mdp-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-mongo
    ports:
      - '5000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.production
    networks:
      - default
      - internal-client

  mdp-mongo:
    image: mongo:6.0.3
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017'
    environment:
      - MONGO_INITDB_DATABASE=mdp-mongo
      - MONGO_INITDB_ROOT_USERNAME=mdp-user
      - MONGO_INITDB_ROOT_PASSWORD=mdp-password
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default

networks:
  default:
    name: mdp-default
  internal-client:
    name: mdp-client
